In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
%matplotlib inline

In [2]:
df=pd.read_csv("PHL-EC-Dataset.csv")

In [3]:
df.head()

,P. Name,P. Name Kepler,P. Name KOI,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),...,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,P. Disc. Method,P. Disc. Year,Unnamed: 68
0,1RXS 1609 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,4451.16,...,0,0,0.05,0,0,0,1,Imaging,2008,NaN
1,1SWASP J1407 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,6358.80,6358.80,...,0,0,0.07,0,0,0,1,Primary Transit,2012,NaN
2,2M 0103-55(AB) b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,4133.22,4133.22,...,0,0,0.06,0,0,0,1,Imaging,2013,NaN
3,2M 0122-24 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,6358.80,...,0,0,0.08,0,0,0,1,Imaging,2013,NaN
4,2M 0219-39 b,NaN,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,NaN,4419.37,...,0,0,0.06,0,0,0,1,Imaging,2015,NaN

In [4]:
df.columns

Index(['P. Name', 'P. Name Kepler', 'P. Name KOI', 'P. Zone Class',
       'P. Mass Class', 'P. Composition Class', 'P. Atmosphere Class',
       'P. Habitable Class', 'P. Min Mass (EU)', 'P. Mass (EU)',
       'P. Max Mass (EU)', 'P. Radius (EU)', 'P. Density (EU)',
       'P. Gravity (EU)', 'P. Esc Vel (EU)', 'P. SFlux Min (EU)',
       'P. SFlux Mean (EU)', 'P. SFlux Max (EU)', 'P. Teq Min (K)',
       'P. Teq Mean (K)', 'P. Teq Max (K)', 'P. Ts Min (K)', 'P. Ts Mean (K)',
       'P. Ts Max (K)', 'P. Surf Press (EU)', 'P. Mag', 'P. Appar Size (deg)',
       'P. Period (days)', 'P. Sem Major Axis (AU)', 'P. Eccentricity',
       'P. Mean Distance (AU)', 'P. Inclination (deg)', 'P. Omega (deg)',
       'S. Name', 'S. Name HD', 'S. Name HIP', 'S. Constellation', 'S. Type',
       'S. Mass (SU)', 'S. Radius (SU)', 'S. Teff (K)', 'S. Luminosity (SU)',
       'S. [Fe/H]', 'S. Age (Gyrs)', 'S. Appar Mag', 'S. Distance (pc)',
       'S. RA (hrs)', 'S. DEC (deg)', 'S. Mag from Planet',
       'S. Size from Planet (deg)', 'S. No. Planets', 'S. No. Planets HZ',
       'S. Hab Zone Min (AU)', 'S. Hab Zone Max (AU)', 'P. HZD', 'P. HZC',
       'P. HZA', 'P. HZI', 'P. SPH', 'P. Int ESI', 'P. Surf ESI', 'P. ESI',
       'S. HabCat', 'P. Habitable', 'P. Hab Moon', 'P. Confirmed',
       'P. Disc. Method', 'P. Disc. Year', 'Unnamed: 68'],
      dtype='object')

In [5]:
df.shape

(3875, 69)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3875 entries, 0 to 3874
Data columns (total 69 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   P. Name                    3875 non-null   object
 1   P. Name Kepler             2328 non-null   object
 2   P. Name KOI                933 non-null    float64
 3   P. Zone Class              3829 non-null   object
 4   P. Mass Class              3869 non-null   object
 5   P. Composition Class       3834 non-null   object
 6   P. Atmosphere Class        3790 non-null   object
 7   P. Habitable Class         3875 non-null   object
 8   P. Min Mass (EU)           1148 non-null   float64
 9   P. Mass (EU)               3842 non-null   float64
 10  P. Max Mass (EU)           0 non-null      float64
 11  P. Radius (EU)             3863 non-null   float64
 12  P. Density (EU)            3834 non-null   float64
 13  P. Gravity (EU)            3834 non-null   float64
 14  P. Esc Vel (EU)            3834 non-null   float64
 15  P. SFlux Min (EU)          3875 non-null   object
 16  P. SFlux Mean (EU)         3875 non-null   object
 17  P. SFlux Max (EU)          3875 non-null   object
 18  P. Teq Min (K)             3829 non-null   float64
 19  P. Teq Mean (K)            3829 non-null   float64
 20  P. Teq Max (K)             3829 non-null   float64
 21  P. Ts Min (K)              1749 non-null   float64
 22  P. Ts Mean (K)             1749 non-null   float64
 23  P. Ts Max (K)              1749 non-null   float64
 24  P. Surf Press (EU)         3834 non-null   float64
 25  P. Mag                     3819 non-null   float64
 26  P. Appar Size (deg)        3863 non-null   float64
 27  P. Period (days)           3725 non-null   float64
 28  P. Sem Major Axis (AU)     3840 non-null   float64
 29  P. Eccentricity            3875 non-null   float64
 30  P. Mean Distance (AU)      3840 non-null   float64
 31  P. Inclination (deg)       724 non-null    float64
 32  P. Omega (deg)             3875 non-null   float64
 33  S. Name                    3875 non-null   object
 34  S. Name HD                 481 non-null    object
 35  S. Name HIP                521 non-null    object
 36  S. Constellation           3875 non-null   object
 37  S. Type                    3791 non-null   object
 38  S. Mass (SU)               3828 non-null   float64
 39  S. Radius (SU)             3763 non-null   float64
 40  S. Teff (K)                3776 non-null   float64
 41  S. Luminosity (SU)         3847 non-null   float64
 42  S. [Fe/H]                  2137 non-null   float64
 43  S. Age (Gyrs)              2322 non-null   float64
 44  S. Appar Mag               2946 non-null   float64
 45  S. Distance (pc)           2688 non-null   float64
 46  S. RA (hrs)                3875 non-null   float64
 47  S. DEC (deg)               3875 non-null   float64
 48  S. Mag from Planet         3829 non-null   float64
 49  S. Size from Planet (deg)  3747 non-null   float64
 50  S. No. Planets             3875 non-null   int64
 51  S. No. Planets HZ          3875 non-null   int64
 52  S. Hab Zone Min (AU)       3760 non-null   float64
 53  S. Hab Zone Max (AU)       3760 non-null   float64
 54  P. HZD                     3829 non-null   float64
 55  P. HZC                     3834 non-null   float64
 56  P. HZA                     3790 non-null   float64
 57  P. HZI                     3790 non-null   float64
 58  P. SPH                     1801 non-null   float64
 59  P. Int ESI                 3875 non-null   int64
 60  P. Surf ESI                3875 non-null   int64
 61  P. ESI                     3827 non-null   float64
 62  S. HabCat                  3875 non-null   int64
 63  P. Habitable               3875 non-null   int64
 64  P. Hab Moon                3875 non-null   int64
 65  P. Confirmed               3875 non-null   int64
 66  P. Disc. Method            3875 non-null   object
 67  P. Disc. Year              3875 non-null   object
 68  Unnamed: 68                2 non-null      float64
dtypes: float64(44), int64(8), object(17)
memory usage: 2.0+ MB

In [7]:
df.describe()

,P. Name KOI,P. Min Mass (EU),P. Mass (EU),P. Max Mass (EU),P. Radius (EU),P. Density (EU),P. Gravity (EU),P. Esc Vel (EU),P. Teq Min (K),P. Teq Mean (K),...,P. HZI,P. SPH,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,Unnamed: 68
count,933.000000,1148.000000,3842.000000,0.0,3863.000000,3834.000000,3834.000000,3834.000000,3829.000000,3829.000000,...,3790.000000,1801.000000,3875.0,3875.0,3827.000000,3875.000000,3875.000000,3875.000000,3875.000000,2.0
mean,1031.676120,1581.618824,578.509357,NaN,5.387137,1.524917,6.375391,4.234549,753.497989,764.532332,...,0.216499,0.009384,0.0,0.0,0.263951,0.066323,0.014194,0.010323,0.994323,2015.0
std,746.112851,3420.572566,2133.583989,NaN,4.805069,14.067200,27.874534,5.806083,497.887357,498.540769,...,0.108930,0.084078,0.0,0.0,0.135512,0.248877,0.118303,0.101087,0.075144,0.0
min,0.000000,0.000000,0.000000,NaN,0.100000,0.000000,0.010000,0.080000,1.100000,1.100000,...,0.000000,0.000000,0.0,0.0,0.030000,0.000000,0.000000,0.000000,0.000000,2015.0
25%,438.010000,34.970000,4.012500,NaN,1.720000,0.200000,0.880000,1.390000,411.100000,421.300000,...,0.110000,0.000000,0.0,0.0,0.190000,0.000000,0.000000,0.000000,1.000000,2015.0
50%,834.030000,373.115000,11.790000,NaN,2.740000,0.850000,1.675000,2.150000,691.400000,702.700000,...,0.230000,0.000000,0.0,0.0,0.270000,0.000000,0.000000,0.000000,1.000000,2015.0
75%,1593.020000,1341.707500,207.140000,NaN,10.195000,1.180000,3.280000,4.250000,1010.500000,1020.100000,...,0.300000,0.000000,0.0,0.0,0.310000,0.000000,0.000000,0.000000,1.000000,2015.0
max,3663.010000,29759.180000,29759.180000,NaN,28.000000,573.180000,898.750000,47.310000,7112.000000,7112.000000,...,0.830000,1.000000,0.0,0.0,0.900000,1.000000,1.000000,1.000000,1.000000,2015.0

In [8]:
pd.options.display.min_rows = 80

In [9]:
df.isnull().sum()

P. Name                         0
P. Name Kepler               1547
P. Name KOI                  2942
P. Zone Class                  46
P. Mass Class                   6
P. Composition Class           41
P. Atmosphere Class            85
P. Habitable Class              0
P. Min Mass (EU)             2727
P. Mass (EU)                   33
P. Max Mass (EU)             3875
P. Radius (EU)                 12
P. Density (EU)                41
P. Gravity (EU)                41
P. Esc Vel (EU)                41
P. SFlux Min (EU)               0
P. SFlux Mean (EU)              0
P. SFlux Max (EU)               0
P. Teq Min (K)                 46
P. Teq Mean (K)                46
P. Teq Max (K)                 46
P. Ts Min (K)                2126
P. Ts Mean (K)               2126
P. Ts Max (K)                2126
P. Surf Press (EU)             41
P. Mag                         56
P. Appar Size (deg)            12
P. Period (days)              150
P. Sem Major Axis (AU)         35
P. Eccentricity                 0
                             ...
S. Radius (SU)                112
S. Teff (K)                    99
S. Luminosity (SU)             28
S. [Fe/H]                    1738
S. Age (Gyrs)                1553
S. Appar Mag                  929
S. Distance (pc)             1187
S. RA (hrs)                     0
S. DEC (deg)                    0
S. Mag from Planet             46
S. Size from Planet (deg)     128
S. No. Planets                  0
S. No. Planets HZ               0
S. Hab Zone Min (AU)          115
S. Hab Zone Max (AU)          115
P. HZD                         46
P. HZC                         41
P. HZA                         85
P. HZI                         85
P. SPH                       2074
P. Int ESI                      0
P. Surf ESI                     0
P. ESI                         48
S. HabCat                       0
P. Habitable                    0
P. Hab Moon                     0
P. Confirmed                    0
P. Disc. Method                 0
P. Disc. Year                   0
Unnamed: 68                  3873
Length: 69, dtype: int64

In [10]:
[features for features in df.columns if df[features].isnull().sum()>0]

['P. Name Kepler',
 'P. Name KOI',
 'P. Zone Class',
 'P. Mass Class',
 'P. Composition Class',
 'P. Atmosphere Class',
 'P. Min Mass (EU)',
 'P. Mass (EU)',
 'P. Max Mass (EU)',
 'P. Radius (EU)',
 'P. Density (EU)',
 'P. Gravity (EU)',
 'P. Esc Vel (EU)',
 'P. Teq Min (K)',
 'P. Teq Mean (K)',
 'P. Teq Max (K)',
 'P. Ts Min (K)',
 'P. Ts Mean (K)',
 'P. Ts Max (K)',
 'P. Surf Press (EU)',
 'P. Mag',
 'P. Appar Size (deg)',
 'P. Period (days)',
 'P. Sem Major Axis (AU)',
 'P. Mean Distance (AU)',
 'P. Inclination (deg)',
 'S. Name HD',
 'S. Name HIP',
 'S. Type',
 'S. Mass (SU)',
 'S. Radius (SU)',
 'S. Teff (K)',
 'S. Luminosity (SU)',
 'S. [Fe/H]',
 'S. Age (Gyrs)',
 'S. Appar Mag',
 'S. Distance (pc)',
 'S. Mag from Planet',
 'S. Size from Planet (deg)',
 'S. Hab Zone Min (AU)',
 'S. Hab Zone Max (AU)',
 'P. HZD',
 'P. HZC',
 'P. HZA',
 'P. HZI',
 'P. SPH',
 'P. ESI',
 'Unnamed: 68']

In [13]:
## Capturing all the nan values for categorical variables
## First lets handle Categorical features which are missing
features_nan=[feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtypes=='O']

for feature in features_nan:
    f1=np.round(df[feature].isnull().mean(),4)
    print("{}: {}% missing values".format(feature,f1*100))

P. Name Kepler: 39.92% missing values
P. Zone Class: 1.1900000000000002% missing values
P. Mass Class: 0.15% missing values
P. Composition Class: 1.06% missing values
P. Atmosphere Class: 2.19% missing values
S. Name HD: 87.59% missing values
S. Name HIP: 86.55000000000001% missing values
S. Type: 2.17% missing values

In [16]:
categorical_features=[feature for feature in df.columns if df[feature].dtype=='O']

In [17]:
categorical_features

['P. Name',
 'P. Name Kepler',
 'P. Zone Class',
 'P. Mass Class',
 'P. Composition Class',
 'P. Atmosphere Class',
 'P. Habitable Class',
 'P. SFlux Min (EU)',
 'P. SFlux Mean (EU)',
 'P. SFlux Max (EU)',
 'S. Name',
 'S. Name HD',
 'S. Name HIP',
 'S. Constellation',
 'S. Type',
 'P. Disc. Method',
 'P. Disc. Year']

In [18]:
df[categorical_features].head(20)

,P. Name,P. Name Kepler,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. SFlux Min (EU),P. SFlux Mean (EU),P. SFlux Max (EU),S. Name,S. Name HD,S. Name HIP,S. Constellation,S. Type,P. Disc. Method,P. Disc. Year
0,1RXS 1609 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,4.08E-06,4.08E-06,4.08E-06,1RXS 1609,NaN,NaN,Sco,K7V,Imaging,2008
1,1SWASP J1407 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.02166914,0.02166914,0.02166914,1SWASP J1407,NaN,NaN,Cen,K,Primary Transit,2012
2,2M 0103-55(AB) b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,3.96E-06,3.96E-06,3.96E-06,2M 0103-55(AB),NaN,NaN,Phe,M,Imaging,2013
3,2M 0122-24 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.03E-05,1.03E-05,1.03E-05,2M 0122-24,NaN,NaN,Cet,M3.5,Imaging,2013
4,2M 0219-39 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,2.37E-07,2.37E-07,2.37E-07,2M 0219-39,NaN,NaN,For,M6,Imaging,2015
5,2M 0441+23 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.26E-07,1.26E-07,1.26E-07,2M 0441+23,NaN,NaN,Tau,M8.5,Imaging,2010
6,2M 0746+20 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,9.06E-06,2.29E-05,7.61E-05,2M 0746+20,NaN,NaN,Gem,NaN,Imaging,2010
7,2M 1207-39 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,2.74E-08,2.74E-08,2.74E-08,2M 1207-39,NaN,NaN,Cen,M8,Imaging,2004
8,2M 1938+46 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,0.1531191,0.1531191,0.1531191,2M 1938+46,NaN,NaN,Cyg,sdB+M,Pulsar,2015
9,2M 2140+16 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.27E-05,2.09E-05,3.68E-05,2M 2140+16,NaN,NaN,Peg,NaN,Imaging,2010
10,2M 2206-20 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.65E-05,1.65E-05,1.65E-05,2M 2206-20,NaN,NaN,Aqr,NaN,Imaging,2010
11,2M 2236+4751 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,7.43E-07,7.43E-07,7.43E-07,2M 2236+4751,NaN,NaN,Lac,K7,Imaging,2016
12,2MASS J1450-7841 Ab,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.56E-09,1.56E-09,1.56E-09,2MASS J1450-7841 Ab,NaN,NaN,Aps,M9p,Imaging,2017
13,2MASS J1450-7841 Bb,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,1.56E-09,1.56E-09,1.56E-09,2MASS J1450-7841 Bb,NaN,NaN,Aps,M8p,Imaging,2017
14,2MASS J2250+2325 b,NaN,NaN,Jovian,gas,NaN,non-habitable,,,,2MASS J2250+2325,NaN,NaN,Peg,M3,Imaging,2017
15,2MASS J11193254 AB b,NaN,NaN,Jovian,gas,NaN,non-habitable,,,,2MASS J11193254 AB,NaN,NaN,Crt,L7,Imaging,2017
16,2M J2126-81 b,NaN,Cold,Jovian,gas,hydrogen-rich,non-habitable,7.82E-09,7.82E-09,7.82E-09,2M J2126-81,NaN,NaN,Oct,M2,Imaging,2016
17,4 Uma b,NaN,Hot,Jovian,gas,hydrogen-rich,non-habitable,72.05381,163.7823,457.8407,4 Uma,NaN,NaN,UMa,K1III,Radial Velocity,2007
18,6 Lyn b,NaN,Hot,Jovian,NaN,NaN,non-habitable,2.393847,3.106028,4.104261,6 Lyn,HD 45410,HIP 31039,Lyn,K0IV,Radial Velocity,2008
19,7 CMa b,NaN,Warm,Jovian,gas,hydrogen-rich,non-habitable,0.4514996,0.6887656,1.104356,7 CMa,HD 47205,HIP 31592,CMa,K1 III,Radial Velocity,2011

In [19]:
for feature in categorical_features:
    print('The feature is {} and number of categories are {}'.format(feature,df[feature].unique()))

The feature is P. Name and number of categories are ['1RXS 1609 b' '1SWASP J1407 b' '2M 0103-55(AB) b' ... 'YZ Cet b'
 'YZ Cet c' 'YZ Cet d']
The feature is P. Name Kepler and number of categories are [nan 'Kepler-2 b' 'Kepler-3 b' ... 'KIC-11152511 b' 'KIC-12454613 b'
 'KIC-12557548 b']
The feature is P. Zone Class and number of categories are ['Cold' nan 'Hot' 'Warm']
The feature is P. Mass Class and number of categories are ['Jovian' 'Superterran' 'Neptunian' 'Terran' 'Subterran' nan 'Mercurian']
The feature is P. Composition Class and number of categories are ['gas' nan 'rocky-water' 'rocky-iron' 'water-gas' 'iron']
The feature is P. Atmosphere Class and number of categories are ['hydrogen-rich' nan 'metals-rich' 'no-atmosphere']
The feature is P. Habitable Class and number of categories are ['non-habitable' 'psychroplanet' 'mesoplanet' 'thermoplanet'
 'hypopsychroplanet']
The feature is P. SFlux Min (EU) and number of categories are ['4.08E-06' '0.02166914' '3.96E-06' ... '9.110547' '4.674975' '2.268338']
The feature is P. SFlux Mean (EU) and number of categories are ['4.08E-06' '0.02166914' '3.96E-06' ... '9.110548' '5.060307' '2.915344']
The feature is P. SFlux Max (EU) and number of categories are ['4.08E-06' '0.02166914' '3.96E-06' ... '9.110549' '5.48639' '3.81074']
The feature is S. Name and number of categories are ['1RXS 1609' '1SWASP J1407' '2M 0103-55(AB)' ... 'YBP1194' 'YBP1514'
 'YZ Cet']
The feature is S. Name HD and number of categories are [nan 'HD 45410' 'HD 47205' 'HD 107383' 'HD 136726' 'HD 221345' 'HD 145675'
 'HD 186427' 'HD 199665' 'HD 90043' 'HD 16232' 'HD 170693' 'HD 217014'
 'HD 75732' 'HD 115617' 'HD 117176' 'HD 15779' 'HD 16400' 'HD 219449'
 'HD 44627' 'HD 12929' 'HD 128621' 'HD 143107' 'HD 28305' 'HD 216956'
 'HD 285968' 'HD 115383' 'HD 204961' 'HD 1237' 'HD 147506' 'HD 233731'
 'HD 351766' 'HD 340099' 'HD 142' 'HD 564' 'HD 1461' 'HD 1502' 'HD 1605'
 'HD 1666' 'HD 1690' 'HD 2039' 'HD 2638' 'HD 2952' 'HD 3651' 'HD 4113'
 'HD 4203' 'HD 4208' 'HD 4308' 'HD 4313' 'HD 4732' 'HD 5319' 'HD 5608'
 'HD 5891' 'HD 6434' 'HD 6718' 'HD 7199' 'HD 7449' 'HD 7924' 'HD 8535'
 'HD 8574' 'HD 8673' 'HD 9446' 'HD 10180' 'HD 10442' 'HD 10647' 'HD 10697'
 'HD 11506' 'HD 11964' 'HD 11977' 'HD 12661' 'HD 13189' 'HD 13908'
 'HD 13931' 'HD 14067' 'HD 16141' 'HD 16175' 'HD 16417' 'HD 17092'
 'HD 17156' 'HD 18742' 'HD 19994' 'HD 20782' 'HD 20794' 'HD 20868'
 'HD 22781' 'HD 23079' 'HD 23127' 'HD 23596' 'HD 24040' 'HD 25171'
 'HD 27442' 'HD 27631' 'HD 27894' 'HD 28185' 'HD 28254' 'HD 28678'
 'HD 30177' 'HD 30562' 'HD 30669' 'HD 30856' 'HD 31253' 'HD 32518'
 'HD 33142' 'HD 33283' 'HD 33564' 'HD 34445' 'HD 37124' 'HD 37605'
 'HD 38283' 'HD 38529' 'HD 38801' 'HD 39091' 'HD 40307' 'HD 40979'
 'HD 41004 A' 'HD 41004 B' 'HD 43197' 'HD 43691' 'HD 44219' 'HD 45350'
 'HD 45364' 'HD 45652' 'HD 46375' 'HD 47186' 'HD 47536' 'HD 48265'
 'HD 49674' 'HD 50499' 'HD 50554' 'HD 52265' 'HD 60532' 'HD 62509'
 'HD 63454' 'HD 63765' 'HD 65216' 'HD 66141' 'HD 66428' 'HD 67087'
 'HD 68988' 'HD 69830' 'HD 70642' 'HD 72659' 'HD 73256' 'HD 73267'
 'HD 73526' 'HD 73534' 'HD 74156' 'HD 75289' 'HD 75784' 'HD 75898'
 'HD 76700' 'HD 77338' 'HD 79498' 'HD 80606' 'HD 81040' 'HD 81688'
 'HD 82886' 'HD 82943' 'HD 83443' 'HD 85390' 'HD 85512' 'HD 86081'
 'HD 86226' 'HD 86264' 'HD 87883' 'HD 88133' 'HD 89307' 'HD 89744'
 'HD 90156' 'HD 92788' 'HD 93083' 'HD 95086' 'HD 95089' 'HD 95127'
 'HD 96063' 'HD 96127' 'HD 96167' 'HD 97658' 'HD 98219' 'HD 98649'
 'HD 99109' 'HD 99492' 'HD 99706' 'HD 100655' 'HD 100777' 'HD 101930'
 'HD 102117' 'HD 102195' 'HD 102272' 'HD 102329' 'HD 102365' 'HD 102956'
 'HD 103197' 'HD 103720' 'HD 103774' 'HD 104067' 'HD 104985' 'HD 106252'
 'HD 106270' 'HD 106515 A' 'HD 106906' 'HD 107148' 'HD 108147' 'HD 108341'
 'HD 108863' 'HD 108874' 'HD 109246' 'HD 109271' 'HD 109749' 'HD 110014'
 'HD 111232' 'HD 113337' 'HD 113538' 'HD 114386' 'HD 114613' 'HD 114729'
 'HD 114762' 'HD 114783' 'HD 116029' 'HD 117207' 'HD 117618' 'HD 118203'
 'HD 120084' 'HD 121504' 'HD 125595' 'HD 125612' 'HD 126614' 'HD 128311'
 'HD 129445' 'HD 130322' 'HD 131496' 'HD 132406' 'HD 134987' 'HD 136418'
 'HD 139357' 'HD 141937' 'HD 142022 A' 'HD 142245' 'HD 142415' 'HD 143361'
 'HD 145377' 'HD 145457' 'HD 145934' 'HD 147018' 'HD 147513' 'HD 148156'
 'HD 148427' 'HD 149026' 'HD 149143' 'HD 150706' 'HD 152079' 'HD 152581'
 'HD 153950' 'HD 154345' 'HD 154672' 'HD 154857' 'HD 155358' 'HD 156279'
 'HD 156411' 'HD 156668' 'HD 158038' 'HD 159243' 'HD 159868' 'HD 162020'
 'HD 163607' 'HD 164509' 'HD 164604' 'HD 164922' 'HD 166724' 'HD 167042'
 'HD 168443' 'HD 168746' 'HD 169830' 'HD 170469' 'HD 171028' 'HD 171238'
 'HD 173416' 'HD 175167' 'HD 175541' 'HD 177830' 'HD 178911 B' 'HD 179079'
 'HD 179949' 'HD 180314' 'HD 180902' 'HD 181342' 'HD 181433' 'HD 181720'
 'HD 183263' 'HD 185269' 'HD 187085' 'HD 187123' 'HD 188015' 'HD 189733'
 'HD 190360' 'HD 190647' 'HD 190984' 'HD 192263' 'HD 192699' 'HD 195019'
 'HD 196050' 'HD 196067' 'HD 196885 A' 'HD 197037' 'HD 200964' 'HD 202206'
 'HD 203030' 'HD 204313' 'HD 204941' 'HD 205739' 'HD 206610' 'HD 207832'
 'HD 208487' 'HD 208527' 'HD 209458' 'HD 210277' 'HD 210702' 'HD 212301'
 'HD 212771' 'HD 213240' 'HD 215497' 'HD 216435' 'HD 216437' 'HD 216536'
 'HD 216770' 'HD 217107' 'HD 217786' 'HD 218566' 'HD 219077' 'HD 219415'
 'HD 219828' 'HD 220074' 'HD 220689' 'HD 220773' 'HD 221287' 'HD 222155'
 'HD 222582' 'HD 224693' 'HD 231701' 'HD 233604' 'HD 240210' 'HD 240237'
 'HD 285507' 'HD 290327' 'HD 330075' 'HD 112410' 'HD 117253' 'HD 121056'
 'HD 137759' 'HD 143567' 'HD 186641' 'HD 203949' 'HD 207229' 'HD 206860'
 'HD 17051' 'HD 218396' 'HD 42176' 'HD 33643' 'HD 179070' 'HD 160691'
 'HD 85503' 'HD 163917' 'HD 141680' 'HD 136512' 'HD 71369' 'HD 120136'
 'HD 54719' 'HD 9826' 'HD 197286' 'HD 10069' 'HD 15082' 'HD 146389'
 'HD 193334' 'HD 358155' 'HD 202678']
The feature is S. Name HIP and number of categories are [nan 'HIP 31039' 'HIP 31592' 'HIP 60202' 'HIP 74793' 'HIP 116076'
 'HIP 79248' 'HIP 96901' 'HIP 103527' 'HIP 50887' 'HIP 12184' 'HIP 90344'
 'HIP 113357' 'HIP 43587' 'HIP 64924' 'HIP 65721' 'HIP 11791' 'HIP 12247'
 'HIP 114855' 'HIP 30034' 'HIP 9884' 'HIP 71681' 'HIP 104780' 'HIP 78407'
 'HIP 27803' 'HIP 49067' 'HIP 90979' 'HIP 2247' 'HIP 78159' 'HIP 20889'
 'HIP 113368' 'HIP 19394' 'HIP 21932' 'HIP 22627' 'HIP 43790' 'HIP 56528'
 'HIP 57087' 'HIP 64792' 'HIP 74995' 'HIP 83043' 'HIP 85523' 'HIP 85647'
 'HIP 86162' 'HIP 106440' 'HIP 109388' 'HIP 113020' 'HIP 1292' 'HIP 80076'
 'HIP 97657' 'HIP 522' 'HIP 801' 'HIP 1499' 'HIP 1547' 'HIP 1640'
 'HIP 1666' 'HIP 1692' 'HIP 1931' 'HIP 2350' 'HIP 2611' 'HIP 3093'
 'HIP 3391' 'HIP 3502' 'HIP 3479' 'HIP 3497' 'HIP 3574' 'HIP 3834'
 'HIP 4297' 'HIP 4552' 'HIP 4715' 'HIP 5054' 'HIP 5301' 'HIP 5529'
 'HIP 5806' 'HIP 6379' 'HIP 6511' 'HIP 6643' 'HIP 6702' 'HIP 7245'
 'HIP 7599' 'HIP 7978' 'HIP 8159' 'HIP 8770' 'HIP 9094' 'HIP 8928'
 'HIP 9683' 'HIP 10085' 'HIP 10743' 'HIP 10626' 'HIP 10657' 'HIP 12048'
 'HIP 12191' 'HIP 12186' 'HIP 13192' 'HIP 13993' 'HIP 14954' 'HIP 15527'
 'HIP 15510' 'HIP 15578' 'HIP 17187' 'HIP 17096' 'HIP 17054' 'HIP 17747'
 'HIP 17960' 'HIP 18387' 'HIP 19921' 'HIP 20199' 'HIP 20277' 'HIP 20723'
 'HIP 20606' 'HIP 21109' 'HIP 21850' 'HIP 22336' 'HIP 22320' 'HIP 22491'
 'HIP 22826' 'HIP 24003' 'HIP 23844' 'HIP 23889' 'HIP 25110' 'HIP 24681'
 'HIP 26381' 'HIP 26664' 'HIP 26380' 'HIP 27253' 'HIP 27384' 'HIP 26394'
 'HIP 27887' 'HIP 28767' 'HIP 28393 A' 'HIP 28393 B' 'HIP 29550'
 'HIP 30057' 'HIP 30114' 'HIP 30860' 'HIP 30579' 'HIP 30905' 'HIP 31246'
 'HIP 31540' 'HIP 31688' 'HIP 31895' 'HIP 32916' 'HIP 32970' 'HIP 33212'
 'HIP 33719' 'HIP 36795' 'HIP 37826' 'HIP 37284' 'HIP 38041' 'HIP 38558'
 'HIP 39311' 'HIP 39417' 'HIP 39767' 'HIP 40687' 'HIP 40693' 'HIP 40952'
 'HIP 42030' 'HIP 42214' 'HIP 42202' 'HIP 42282' 'HIP 42446' 'HIP 42723'
 'HIP 43177' 'HIP 43569' 'HIP 43674' 'HIP 43686' 'HIP 44291' 'HIP 45406'
 'HIP 45982' 'HIP 46076' 'HIP 46471' 'HIP 47087' 'HIP 47007' 'HIP 47202'
 'HIP 48235' 'HIP 48331' 'HIP 48711' 'HIP 48739' 'HIP 48780' 'HIP 49699'
 'HIP 49813' 'HIP 50473' 'HIP 50786' 'HIP 50921' 'HIP 52409' 'HIP 52521'
 'HIP 53524' 'HIP 53666' 'HIP 53733' 'HIP 54158' 'HIP 54232' 'HIP 54195'
 'HIP 54906' 'HIP 55174' 'HIP 55409' 'HIP 55664' 'HIP 55848' 'HIP 55994'
 'HIP 56508' 'HIP 56572' 'HIP 57172' 'HIP 57291' 'HIP 57370' 'HIP 57428'
 'HIP 57467' 'HIP 57443' 'HIP 57820' 'HIP 57931' 'HIP 58237' 'HIP 58263'
 'HIP 58451' 'HIP 58952' 'HIP 59610' 'HIP 59625' 'HIP 59743 A' 'HIP 59960'
 'HIP 60081' 'HIP 60644' 'HIP 60788' 'HIP 61020' 'HIP 61028' 'HIP 61177'
 'HIP 61300' 'HIP 61595 A' 'HIP 61740' 'HIP 62534' 'HIP 63584' 'HIP 63833'
 'HIP 64295' 'HIP 64408' 'HIP 64459' 'HIP 64426' 'HIP 64457' 'HIP 65117'
 'HIP 65808' 'HIP 66047' 'HIP 66192' 'HIP 66903' 'HIP 68162' 'HIP 70170'
 'HIP 70123' 'HIP 70623' 'HIP 71395' 'HIP 72203' 'HIP 72339' 'HIP 72845'
 'HIP 73146' 'HIP 74500' 'HIP 74961' 'HIP 76311' 'HIP 77740' 'HIP 79242'
 'HIP 77783' 'HIP 78169' 'HIP 78521' 'HIP 79346' 'HIP 79219' 'HIP 80250'
 'HIP 80337' 'HIP 80680' 'HIP 80687' 'HIP 80838' 'HIP 81022' 'HIP 80902'
 'HIP 82632' 'HIP 82651' 'HIP 83547' 'HIP 83389' 'HIP 83983' 'HIP 84069'
 'HIP 83949' 'HIP 84171' 'HIP 84787' 'HIP 84607' 'HIP 85294' 'HIP 85911'
 'HIP 86375' 'HIP 87330' 'HIP 87601' 'HIP 88268' 'HIP 88414' 'HIP 88348'
 'HIP 89354' 'HIP 89047' 'HIP 89844' 'HIP 90004' 'HIP 90485' 'HIP 90593'
 'HIP 91085' 'HIP 91852' 'HIP 93281' 'HIP 92895' 'HIP 93746' 'HIP 94075'
 'HIP 94256' 'HIP 94645' 'HIP 94576' 'HIP 94951' 'HIP 95124' 'HIP 95467'
 'HIP 95262' 'HIP 95740' 'HIP 96507' 'HIP 97546' 'HIP 97336' 'HIP 97769'
 'HIP 98505' 'HIP 98767' 'HIP 99115' 'HIP 99496' 'HIP 99711' 'HIP 99894'
 'HIP 100970' 'HIP 101806' 'HIP 102125' 'HIP 101966' 'HIP 101948'
 'HIP 104202' 'HIP 104903' 'HIP 105232' 'HIP 106006' 'HIP 106353'
 'HIP 106824' 'HIP 107251' 'HIP 107985' 'HIP 108375' 'HIP 108296'
 'HIP 108859' 'HIP 109378' 'HIP 109577' 'HIP 110852' 'HIP 110813'
 'HIP 111143' 'HIP 112441' 'HIP 113044' 'HIP 113137' 'HIP 113238'
 'HIP 113421' 'HIP 113834' 'HIP 114322' 'HIP 114699' 'HIP 115100'
 'HIP 115218' 'HIP 115662' 'HIP 115697' 'HIP 116084' 'HIP 116616'
 'HIP 116906' 'HIP 118319' 'HIP 96078' 'HIP 114840' 'HIP 19207'
 'HIP 25191' 'HIP 77517' 'HIP 5158' 'HIP 12961' 'HIP 14810' 'HIP 57050'
 'HIP 57274' 'HIP 63242' 'HIP 65891' 'HIP 67851' 'HIP 70849' 'HIP 75458'
 'HIP 78530' 'HIP 79431' 'HIP 91258' 'HIP 97233' 'HIP 105854' 'HIP 107773'
 'HIP 116454' 'HIP 107350' 'HIP 12653' 'HIP 114189' 'HIP 29301'
 'HIP 24323' 'HIP 94112' 'HIP 94931' 'HIP 86796' 'HIP 48455' 'HIP 88048'
 'HIP 77578' 'HIP 75049' 'HIP 41704' 'HIP 63510' 'HIP 67275' 'HIP 34693'
 'HIP 7513' 'HIP 7562' 'HIP 11397']
The feature is S. Constellation and number of categories are ['Sco' 'Cen' 'Phe' 'Cet' 'For' 'Tau' 'Gem' 'Cyg' 'Peg' 'Aqr' 'Lac' 'Aps'
 'Crt' 'Oct' 'UMa' 'Lyn' 'CMa' 'UMi' 'Com' 'And' 'Her' 'Del' 'Boo' 'Sex'
 'Ari' 'Vir' 'Dra' 'Eri' 'Cnc' 'Pic' 'Leo' 'Ser' 'Psc' 'Per' 'Ori' 'Sct'
 'Cir' 'Col' 'Cha' 'Mon' 'Aql' 'Oph' 'Vel' 'Sgr' 'Lib' 'CrB' 'Ind' 'Lyr'
 'PsA' 'Cep' 'Dor' 'Lep' 'CMi' 'Pyx' 'Hya' 'Ara' 'Cap' 'Gru' 'Hyi' 'Lup'
 'Aur' 'CVn' 'Sge' 'Tri' 'Vul' 'Equ' 'Scl' 'Ant' 'Pav' 'Tel' 'Tuc' 'Pup'
 'Cas' 'Ret' 'Cam' 'Hor' 'Cae' 'Men' 'Car' 'Vol' 'LMi' 'Crv' 'Cru' 'Mus'
 'Nor' 'TrA' 'CrA' 'Mic']
The feature is S. Type and number of categories are ['K7V' 'K' 'M' 'M3.5' 'M6' 'M8.5' nan 'M8' 'sdB+M' 'K7' 'M9p' 'M8p' 'M3'
 'L7' 'M2' 'K1III' 'K0IV' 'K1 III' 'K0' 'G8 III' 'M9' 'K4III' 'K0III'
 'K0 V' 'G2.5 V' 'G6III' 'G3IV' 'G5' 'F6V' 'F6 V' 'K1.5III' 'G0V' 'F0IV'
 'G2 IV' 'K0IV-V' 'G5V' 'G4 V' 'G3III' 'G5III' 'K0 III' 'K2 V' 'K5III'
 'K2III' 'K1V' 'K5' 'K2V' 'K5V' 'K2II' 'KO' 'K7V/M0V' 'K3V' 'A3V' 'A6V'
 'M1V' 'T9.5' 'T7' 'M3.25' 'K4IV' 'G7V' 'F3V' 'F8V' 'F9V' 'K0V' 'G3V'
 'G2V' 'F7V' 'G9V' 'F8IV' 'G0IV' 'G8IV' 'G2' 'G8/9IV' 'KOV' 'G2IV' 'G0VI'
 'M3 PMS' 'M0.5V' 'AM Her' 'SdB D' 'M0' 'M4.5' 'M0.0V' 'G' 'M3.0' 'M0V'
 'M1.0V' 'M3.0V' 'F' 'F9IV' 'M2.5V' 'M1.5V' 'K3' 'A3 V' 'M7.25' 'M4'
 'K1III-IV' 'M2V' 'M1 V' 'M3.5V' 'M1.5' 'M2.5' 'GOV' 'M1' 'K4/M1/M3'
 'M4 V' 'G6 V' 'K6V' 'DBe D' 'K7eV' 'F8' 'K4' 'G4' 'G3' 'K1' 'G8' 'F/G'
 'A5' 'A' 'K2' 'G0' 'G4V' 'G1 IV' 'A0V' 'K0D' 'K1 IV' 'F7 V' 'G2/G3 IV-V'
 'G5 V' 'G5 D' 'K0 IV' 'G5IV' 'G5D' 'G3 IV' 'KOIV/V' 'G1V' 'K2 IV' 'G5 IV'
 'G8.5 III' 'K2 II' 'G9 III' 'G9IV' 'F8 V' 'G8V' 'G9.5V' 'G2 V' 'K3/4IV'
 'F8/G0 V' 'K2 IV a' 'G1IV/V' 'G8 V' 'F9.5V' 'G4 IV' 'K2.5V' 'K1 V'
 'G1.5V' 'G8-K0' 'G IV' 'G0 V' 'K2 III' 'F6IV-V' 'K0IIIb' 'K4 V' 'G5IV/V'
 'G5 IV-V' 'G8/K0' 'K3 IV' 'G2/G3' 'K0III-IV' 'G1IV' 'K3 V' 'A8III'
 'K0III/IV' 'G9III' 'G6V' 'F5V' 'K9V' 'G3-4' 'G3 V' 'G8VI/V' 'G6' 'G7 III'
 'K4V' 'G6IV' 'K0/K1V' 'G2/G3 V' 'G1 V' 'F5' 'G3/G5V' 'G0 IV' 'F8IV/V'
 'G8.5V' 'K5 III' 'A1V' 'A7V' 'G5 IV/V' 'A9V' 'K3IV' 'K1-K2' 'G6 IV'
 'G3 IV-V' 'A0' 'M1III' 'K1IV' 'G0.5V' 'G4 IV-V' 'G8 IV' 'M2III' 'F9'
 'F9IV/V' 'K3III' 'M4V' 'G8III' 'B9.5V' 'A2V' 'KOIII' 'B6' 'B9V' 'M3V'
 'G0V pecul.' 'A5V' 'Catac. var.' 'WD' 'K7.5 V' 'M2.5 V' 'G9 V' 'M0.0'
 'M0 V' 'M1.0 V' 'G7 V' 'M3.3' 'F9 V' 'K5.5' 'M3 V' 'B9IV' 'K1IVa' 'F4V'
 'A8V' 'F6IV' 'F7IV' 'F5IV' 'G0V/G0IV' 'F+M' 'B' 'sdB' 'G9/K0' 'M5V'
 'F7V/M' 'F6' 'G9IIIb' 'M5' 'A8' 'A2' 'Brown Dwarf' 'M05' 'M5.1' 'WD+M'
 'B D' 'M/K' 'sdB2VII' 'G or K' 'F3' 'G4II-III' 'F7' 'G9' 'M5.5V' 'PSR'
 'G6.5' 'M0.5' 'M0 D' 'DAZ8+dM' 'T5.5' 'T2.5' 'K4-M2.5' 'G8.5 V' 'M8 D'
 'M7' 'DD D' 'M7.5' 'F4' 'F8-9' 'F8-G0' 'G1' 'kov' 'G7' 'F2' 'K6' 'F1 V'
 'F1V' 'DQ D' 'T 8.5' 'T8.5' 'T8' 'Y2' 'K3.5V']
The feature is P. Disc. Method and number of categories are ['Imaging' 'Primary Transit' 'Pulsar' 'Radial Velocity' 'Other'
 'radial velocity' 'Astrometry' 'Transit' 'TTV' 'transit' 'Microlensing']
The feature is P. Disc. Year and number of categories are ['2008' '2012' '2013' '2015' '2010' '2004' '2016' '2017' '2007' '2011'
 '2009' '2002' '1996' '2018' '2001' '1995' '2003' '2005' '1998' '2014'
 '2000' '2006' '1999' '1989' '          ' '1992' '1988' ' TTV']

In [20]:
for feature in categorical_features:
    print('The feature is {} and number of categories are {}'.format(feature,len(df[feature].unique())))

The feature is P. Name and number of categories are 3875
The feature is P. Name Kepler and number of categories are 2329
The feature is P. Zone Class and number of categories are 4
The feature is P. Mass Class and number of categories are 7
The feature is P. Composition Class and number of categories are 6
The feature is P. Atmosphere Class and number of categories are 4
The feature is P. Habitable Class and number of categories are 5
The feature is P. SFlux Min (EU) and number of categories are 3824
The feature is P. SFlux Mean (EU) and number of categories are 3823
The feature is P. SFlux Max (EU) and number of categories are 3824
The feature is S. Name and number of categories are 2906
The feature is S. Name HD and number of categories are 375
The feature is S. Name HIP and number of categories are 389
The feature is S. Constellation and number of categories are 88
The feature is S. Type and number of categories are 294
The feature is P. Disc. Method and number of categories are 11
The feature is P. Disc. Year and number of categories are 28

In [21]:
df['P. Habitable Class'].replace(to_replace=['thermoplanet','hypopsychroplanet'],value=['mesoplanet','non-habitable'],inplace=True)

<ipython-input-21-b95a07cc29ac>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['P. Habitable Class'].replace(to_replace=['thermoplanet','hypopsychroplanet'],value=['mesoplanet','non-habitable'],inplace=True)

In [22]:
from sklearn import preprocessing
label=preprocessing.LabelEncoder()
df['P. Habitable Class']=label.fit_transform(df['P. Habitable Class'])
##df['P. Habitable Class'].replace(to_replace=['non-habitable','mesoplanet','psychroplanet'],value=[0,1,2],inplace=True)
##df['P. Habitable Class'].replace(to_replace='thermoplanet',value=2,inplace=True)

In [23]:
df['P. Habitable Class'].unique()

array([1, 2, 0])

In [24]:
df['P. Zone Class'].replace(to_replace=np.nan,value='missing',inplace=True)
##df['P. Zone Class']=df['P. Zone Class'].fillna(value='missing',inplace=True)

<ipython-input-24-4c0f81373db5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['P. Zone Class'].replace(to_replace=np.nan,value='missing',inplace=True)

In [25]:
df['P. Zone Class'].unique()

array(['Cold', 'missing', 'Hot', 'Warm'], dtype=object)

In [26]:
df.drop(df.loc[df['P. Zone Class']=='missing'].index, inplace=True)

In [27]:
df['P. Zone Class'].unique()

array(['Cold', 'Hot', 'Warm'], dtype=object)

In [28]:
from sklearn import preprocessing
label=preprocessing.LabelEncoder()
df['P. Zone Class']=label.fit_transform(df['P. Zone Class'])

In [29]:
df['P. Zone Class'].unique()

array([0, 1, 2])

In [30]:
df.head()

,P. Name,P. Name Kepler,P. Name KOI,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),...,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,P. Disc. Method,P. Disc. Year,Unnamed: 68
0,1RXS 1609 b,NaN,NaN,0,Jovian,gas,hydrogen-rich,1,NaN,4451.16,...,0,0,0.05,0,0,0,1,Imaging,2008,NaN
1,1SWASP J1407 b,NaN,NaN,0,Jovian,gas,hydrogen-rich,1,6358.80,6358.80,...,0,0,0.07,0,0,0,1,Primary Transit,2012,NaN
2,2M 0103-55(AB) b,NaN,NaN,0,Jovian,gas,hydrogen-rich,1,4133.22,4133.22,...,0,0,0.06,0,0,0,1,Imaging,2013,NaN
3,2M 0122-24 b,NaN,NaN,0,Jovian,gas,hydrogen-rich,1,NaN,6358.80,...,0,0,0.08,0,0,0,1,Imaging,2013,NaN
4,2M 0219-39 b,NaN,NaN,0,Jovian,gas,hydrogen-rich,1,NaN,4419.37,...,0,0,0.06,0,0,0,1,Imaging,2015,NaN

In [31]:
df.drop(['P. Name Kepler','P. Name KOI'],axis=1,inplace=True)

In [32]:
df.head()

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Max Mass (EU),P. Radius (EU),...,P. Int ESI,P. Surf ESI,P. ESI,S. HabCat,P. Habitable,P. Hab Moon,P. Confirmed,P. Disc. Method,P. Disc. Year,Unnamed: 68
0,1RXS 1609 b,0,Jovian,gas,hydrogen-rich,1,NaN,4451.16,NaN,19.04,...,0,0,0.05,0,0,0,1,Imaging,2008,NaN
1,1SWASP J1407 b,0,Jovian,gas,hydrogen-rich,1,6358.80,6358.80,NaN,10.94,...,0,0,0.07,0,0,0,1,Primary Transit,2012,NaN
2,2M 0103-55(AB) b,0,Jovian,gas,hydrogen-rich,1,4133.22,4133.22,NaN,11.40,...,0,0,0.06,0,0,0,1,Imaging,2013,NaN
3,2M 0122-24 b,0,Jovian,gas,hydrogen-rich,1,NaN,6358.80,NaN,11.20,...,0,0,0.08,0,0,0,1,Imaging,2013,NaN
4,2M 0219-39 b,0,Jovian,gas,hydrogen-rich,1,NaN,4419.37,NaN,16.13,...,0,0,0.06,0,0,0,1,Imaging,2015,NaN

In [33]:
df.drop(['S. Name','S. Name HD','S. Name HIP','S. Constellation','S. Type'],axis=1,inplace=True)

In [34]:
df.drop(['P. Disc. Method','P. Disc. Year'],axis=1,inplace=True)

In [35]:
df.drop(['P. Confirmed','P. Hab Moon','S. HabCat','P. Surf ESI','P. Int ESI','P. SPH','S. No. Planets HZ','S. No. Planets'],axis=1,inplace=True)

In [36]:
df.drop(['S. Distance (pc)','S. DEC (deg)','S. RA (hrs)','P. Ts Max (K)','P. Ts Mean (K)','P. Ts Min (K)','P. Max Mass (EU)'],axis=1,inplace=True)

In [37]:
df.head()

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Radius (EU),P. Density (EU),...,S. Size from Planet (deg),S. Hab Zone Min (AU),S. Hab Zone Max (AU),P. HZD,P. HZC,P. HZA,P. HZI,P. ESI,P. Habitable,Unnamed: 68
0,1RXS 1609 b,0,Jovian,gas,hydrogen-rich,1,NaN,4451.16,19.04,0.64,...,0.0022,0.540,1.362,800.07,23.51,85.62,0.00,0.05,0,NaN
1,1SWASP J1407 b,0,Jovian,gas,hydrogen-rich,1,6358.80,6358.80,10.94,4.86,...,0.1353,0.461,1.143,9.07,15.30,45.41,0.02,0.07,0,NaN
2,2M 0103-55(AB) b,0,Jovian,gas,hydrogen-rich,1,4133.22,4133.22,11.40,2.79,...,0.0024,0.136,0.347,793.67,12.57,107.44,0.00,0.06,0,NaN
3,2M 0122-24 b,0,Jovian,gas,hydrogen-rich,1,NaN,6358.80,11.20,4.53,...,0.0039,0.136,0.347,490.45,15.72,119.46,0.00,0.08,0,NaN
4,2M 0219-39 b,0,Jovian,gas,hydrogen-rich,1,NaN,4419.37,16.13,1.05,...,0.0009,0.062,0.165,3028.82,19.46,133.25,0.00,0.06,0,NaN

In [38]:
df.drop(['Unnamed: 68'],axis=1,inplace=True)

In [39]:
df.head()

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Radius (EU),P. Density (EU),...,S. Mag from Planet,S. Size from Planet (deg),S. Hab Zone Min (AU),S. Hab Zone Max (AU),P. HZD,P. HZC,P. HZA,P. HZI,P. ESI,P. Habitable
0,1RXS 1609 b,0,Jovian,gas,hydrogen-rich,1,NaN,4451.16,19.04,0.64,...,-13.2,0.0022,0.540,1.362,800.07,23.51,85.62,0.00,0.05,0
1,1SWASP J1407 b,0,Jovian,gas,hydrogen-rich,1,6358.80,6358.80,10.94,4.86,...,-22.5,0.1353,0.461,1.143,9.07,15.30,45.41,0.02,0.07,0
2,2M 0103-55(AB) b,0,Jovian,gas,hydrogen-rich,1,4133.22,4133.22,11.40,2.79,...,-13.2,0.0024,0.136,0.347,793.67,12.57,107.44,0.00,0.06,0
3,2M 0122-24 b,0,Jovian,gas,hydrogen-rich,1,NaN,6358.80,11.20,4.53,...,-14.2,0.0039,0.136,0.347,490.45,15.72,119.46,0.00,0.08,0
4,2M 0219-39 b,0,Jovian,gas,hydrogen-rich,1,NaN,4419.37,16.13,1.05,...,-10.1,0.0009,0.062,0.165,3028.82,19.46,133.25,0.00,0.06,0

In [40]:
df.columns

Index(['P. Name', 'P. Zone Class', 'P. Mass Class', 'P. Composition Class',
       'P. Atmosphere Class', 'P. Habitable Class', 'P. Min Mass (EU)',
       'P. Mass (EU)', 'P. Radius (EU)', 'P. Density (EU)', 'P. Gravity (EU)',
       'P. Esc Vel (EU)', 'P. SFlux Min (EU)', 'P. SFlux Mean (EU)',
       'P. SFlux Max (EU)', 'P. Teq Min (K)', 'P. Teq Mean (K)',
       'P. Teq Max (K)', 'P. Surf Press (EU)', 'P. Mag', 'P. Appar Size (deg)',
       'P. Period (days)', 'P. Sem Major Axis (AU)', 'P. Eccentricity',
       'P. Mean Distance (AU)', 'P. Inclination (deg)', 'P. Omega (deg)',
       'S. Mass (SU)', 'S. Radius (SU)', 'S. Teff (K)', 'S. Luminosity (SU)',
       'S. [Fe/H]', 'S. Age (Gyrs)', 'S. Appar Mag', 'S. Mag from Planet',
       'S. Size from Planet (deg)', 'S. Hab Zone Min (AU)',
       'S. Hab Zone Max (AU)', 'P. HZD', 'P. HZC', 'P. HZA', 'P. HZI',
       'P. ESI', 'P. Habitable'],
      dtype='object')

In [41]:
df=df[df['P. Mass Class'].notna()]

In [42]:
df['P. Mass Class'].unique()

array(['Jovian', 'Superterran', 'Neptunian', 'Terran', 'Subterran',
       'Mercurian'], dtype=object)

In [43]:
from sklearn import preprocessing
label=preprocessing.LabelEncoder()
df['P. Mass Class']=label.fit_transform(df['P. Mass Class'])

In [44]:
df['P. Mass Class'].unique()

array([0, 4, 2, 5, 3, 1])

In [45]:
df=df[df['P. Composition Class'].notna()]

In [46]:
df['P. Composition Class'].unique()

array(['gas', 'rocky-water', 'rocky-iron', 'water-gas', 'iron'],
      dtype=object)

In [47]:
from sklearn import preprocessing
label=preprocessing.LabelEncoder()
df['P. Composition Class']=label.fit_transform(df['P. Composition Class'])

In [48]:
df['P. Composition Class'].unique()

array([0, 3, 2, 4, 1])

In [49]:
df=df[df['P. Atmosphere Class'].notna()]

In [50]:
from sklearn import preprocessing
label=preprocessing.LabelEncoder()
df['P. Atmosphere Class']=label.fit_transform(df['P. Atmosphere Class'])

In [51]:
df['P. Atmosphere Class'].unique()

array([0, 1, 2])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3789 entries, 0 to 3874
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   P. Name                    3789 non-null   object
 1   P. Zone Class              3789 non-null   int64
 2   P. Mass Class              3789 non-null   int64
 3   P. Composition Class       3789 non-null   int64
 4   P. Atmosphere Class        3789 non-null   int64
 5   P. Habitable Class         3789 non-null   int64
 6   P. Min Mass (EU)           1113 non-null   float64
 7   P. Mass (EU)               3789 non-null   float64
 8   P. Radius (EU)             3789 non-null   float64
 9   P. Density (EU)            3789 non-null   float64
 10  P. Gravity (EU)            3789 non-null   float64
 11  P. Esc Vel (EU)            3789 non-null   float64
 12  P. SFlux Min (EU)          3789 non-null   object
 13  P. SFlux Mean (EU)         3789 non-null   object
 14  P. SFlux Max (EU)          3789 non-null   object
 15  P. Teq Min (K)             3789 non-null   float64
 16  P. Teq Mean (K)            3789 non-null   float64
 17  P. Teq Max (K)             3789 non-null   float64
 18  P. Surf Press (EU)         3789 non-null   float64
 19  P. Mag                     3789 non-null   float64
 20  P. Appar Size (deg)        3789 non-null   float64
 21  P. Period (days)           3667 non-null   float64
 22  P. Sem Major Axis (AU)     3789 non-null   float64
 23  P. Eccentricity            3789 non-null   float64
 24  P. Mean Distance (AU)      3789 non-null   float64
 25  P. Inclination (deg)       710 non-null    float64
 26  P. Omega (deg)             3789 non-null   float64
 27  S. Mass (SU)               3784 non-null   float64
 28  S. Radius (SU)             3708 non-null   float64
 29  S. Teff (K)                3705 non-null   float64
 30  S. Luminosity (SU)         3789 non-null   float64
 31  S. [Fe/H]                  2122 non-null   float64
 32  S. Age (Gyrs)              2286 non-null   float64
 33  S. Appar Mag               2888 non-null   float64
 34  S. Mag from Planet         3789 non-null   float64
 35  S. Size from Planet (deg)  3708 non-null   float64
 36  S. Hab Zone Min (AU)       3705 non-null   float64
 37  S. Hab Zone Max (AU)       3705 non-null   float64
 38  P. HZD                     3789 non-null   float64
 39  P. HZC                     3789 non-null   float64
 40  P. HZA                     3789 non-null   float64
 41  P. HZI                     3789 non-null   float64
 42  P. ESI                     3789 non-null   float64
 43  P. Habitable               3789 non-null   int64
dtypes: float64(34), int64(6), object(4)
memory usage: 1.3+ MB

In [53]:
df.shape

(3789, 44)

In [54]:
df.head()

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Radius (EU),P. Density (EU),...,S. Mag from Planet,S. Size from Planet (deg),S. Hab Zone Min (AU),S. Hab Zone Max (AU),P. HZD,P. HZC,P. HZA,P. HZI,P. ESI,P. Habitable
0,1RXS 1609 b,0,0,0,0,1,NaN,4451.16,19.04,0.64,...,-13.2,0.0022,0.540,1.362,800.07,23.51,85.62,0.00,0.05,0
1,1SWASP J1407 b,0,0,0,0,1,6358.80,6358.80,10.94,4.86,...,-22.5,0.1353,0.461,1.143,9.07,15.30,45.41,0.02,0.07,0
2,2M 0103-55(AB) b,0,0,0,0,1,4133.22,4133.22,11.40,2.79,...,-13.2,0.0024,0.136,0.347,793.67,12.57,107.44,0.00,0.06,0
3,2M 0122-24 b,0,0,0,0,1,NaN,6358.80,11.20,4.53,...,-14.2,0.0039,0.136,0.347,490.45,15.72,119.46,0.00,0.08,0
4,2M 0219-39 b,0,0,0,0,1,NaN,4419.37,16.13,1.05,...,-10.1,0.0009,0.062,0.165,3028.82,19.46,133.25,0.00,0.06,0

In [55]:
data=df

In [56]:
df.rename(columns={'P. SFlux Min (EU)':'PSFluxMin','P. SFlux Mean (EU)':'PSFluxMean','P. SFlux Max (EU)':'PSFluxMax'},inplace=True)

In [57]:
df['PSFluxMin']=df.PSFluxMin.astype(float)
df['PSFluxMean']=df.PSFluxMean.astype(float)
df['PSFluxMax']=df.PSFluxMax.astype(float)

In [58]:
df['PSFluxMin']=df.PSFluxMin.astype(float)
df['PSFluxMean']=df.PSFluxMean.astype(float)
df['PSFluxMax']=df.PSFluxMax.astype(float)

In [59]:
df['PSFluxMin'].head(20)

0     4.080000e-06
1     2.166914e-02
2     3.960000e-06
3     1.030000e-05
4     2.370000e-07
5     1.260000e-07
6     9.060000e-06
7     2.740000e-08
8     1.531191e-01
9     1.270000e-05
10    1.650000e-05
11    7.430000e-07
12    1.560000e-09
13    1.560000e-09
16    7.820000e-09
17    7.205381e+01
19    4.514996e-01
20    1.799768e+02
21    6.495758e+01
22    2.970000e-10
Name: PSFluxMin, dtype: float64

In [60]:
df.columns

Index(['P. Name', 'P. Zone Class', 'P. Mass Class', 'P. Composition Class',
       'P. Atmosphere Class', 'P. Habitable Class', 'P. Min Mass (EU)',
       'P. Mass (EU)', 'P. Radius (EU)', 'P. Density (EU)', 'P. Gravity (EU)',
       'P. Esc Vel (EU)', 'PSFluxMin', 'PSFluxMean', 'PSFluxMax',
       'P. Teq Min (K)', 'P. Teq Mean (K)', 'P. Teq Max (K)',
       'P. Surf Press (EU)', 'P. Mag', 'P. Appar Size (deg)',
       'P. Period (days)', 'P. Sem Major Axis (AU)', 'P. Eccentricity',
       'P. Mean Distance (AU)', 'P. Inclination (deg)', 'P. Omega (deg)',
       'S. Mass (SU)', 'S. Radius (SU)', 'S. Teff (K)', 'S. Luminosity (SU)',
       'S. [Fe/H]', 'S. Age (Gyrs)', 'S. Appar Mag', 'S. Mag from Planet',
       'S. Size from Planet (deg)', 'S. Hab Zone Min (AU)',
       'S. Hab Zone Max (AU)', 'P. HZD', 'P. HZC', 'P. HZA', 'P. HZI',
       'P. ESI', 'P. Habitable'],
      dtype='object')

In [61]:
df.drop(['P. Inclination (deg)'],axis=1,inplace=True)

In [62]:
df.columns

Index(['P. Name', 'P. Zone Class', 'P. Mass Class', 'P. Composition Class',
       'P. Atmosphere Class', 'P. Habitable Class', 'P. Min Mass (EU)',
       'P. Mass (EU)', 'P. Radius (EU)', 'P. Density (EU)', 'P. Gravity (EU)',
       'P. Esc Vel (EU)', 'PSFluxMin', 'PSFluxMean', 'PSFluxMax',
       'P. Teq Min (K)', 'P. Teq Mean (K)', 'P. Teq Max (K)',
       'P. Surf Press (EU)', 'P. Mag', 'P. Appar Size (deg)',
       'P. Period (days)', 'P. Sem Major Axis (AU)', 'P. Eccentricity',
       'P. Mean Distance (AU)', 'P. Omega (deg)', 'S. Mass (SU)',
       'S. Radius (SU)', 'S. Teff (K)', 'S. Luminosity (SU)', 'S. [Fe/H]',
       'S. Age (Gyrs)', 'S. Appar Mag', 'S. Mag from Planet',
       'S. Size from Planet (deg)', 'S. Hab Zone Min (AU)',
       'S. Hab Zone Max (AU)', 'P. HZD', 'P. HZC', 'P. HZA', 'P. HZI',
       'P. ESI', 'P. Habitable'],
      dtype='object')

In [63]:
df['P. Min Mass (EU)'].fillna(value=df['P. Min Mass (EU)'].mean(),inplace=True)

<ipython-input-63-cefe1bdec678>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['P. Min Mass (EU)'].fillna(value=df['P. Min Mass (EU)'].mean(),inplace=True)

In [64]:
df['P. Period (days)'].fillna(value=df['P. Period (days)'].mean(),inplace=True)

<ipython-input-64-8155575a2600>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['P. Period (days)'].fillna(value=df['P. Period (days)'].mean(),inplace=True)

In [65]:
df['S. Mass (SU)'].fillna(value=df['S. Mass (SU)'].mean(),inplace=True)
df['S. Radius (SU)'].fillna(value=df['S. Radius (SU)'].mean(),inplace=True)
df['S. Teff (K)'].fillna(value=df['S. Teff (K)'].mean(),inplace=True)
df['S. [Fe/H]'].fillna(value=df['S. [Fe/H]'].mean(),inplace=True)
df['S. Age (Gyrs)'].fillna(value=df['S. Age (Gyrs)'].mean(),inplace=True)
df['S. Appar Mag'].fillna(value=df['S. Appar Mag'].mean(),inplace=True)

<ipython-input-65-2c5c11e08fa4>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Mass (SU)'].fillna(value=df['S. Mass (SU)'].mean(),inplace=True)
<ipython-input-65-2c5c11e08fa4>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Radius (SU)'].fillna(value=df['S. Radius (SU)'].mean(),inplace=True)
<ipython-input-65-2c5c11e08fa4>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Teff (K)'].fillna(value=df['S. Teff (K)'].mean(),inplace=True)
<ipython-input-65-2c5c11e08fa4>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. [Fe/H]'].fillna(value=df['S. [Fe/H]'].mean(),inplace=True)
<ipython-input-65-2c5c11e08fa4>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Age (Gyrs)'].fillna(value=df['S. Age (Gyrs)'].mean(),inplace=True)
<ipython-input-65-2c5c11e08fa4>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Appar Mag'].fillna(value=df['S. Appar Mag'].mean(),inplace=True)

In [66]:
df['S. Size from Planet (deg)'].fillna(value=df['S. Size from Planet (deg)'].mean(),inplace=True)
df['S. Hab Zone Min (AU)'].fillna(value=df['S. Hab Zone Min (AU)'].mean(),inplace=True)
df['S. Hab Zone Max (AU)'].fillna(value=df['S. Hab Zone Max (AU)'].mean(),inplace=True)

<ipython-input-66-9a7a9132853a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Size from Planet (deg)'].fillna(value=df['S. Size from Planet (deg)'].mean(),inplace=True)
<ipython-input-66-9a7a9132853a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Hab Zone Min (AU)'].fillna(value=df['S. Hab Zone Min (AU)'].mean(),inplace=True)
<ipython-input-66-9a7a9132853a>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['S. Hab Zone Max (AU)'].fillna(value=df['S. Hab Zone Max (AU)'].mean(),inplace=True)

In [68]:
df.shape

(3789, 43)

In [69]:
df.head()

,P. Name,P. Zone Class,P. Mass Class,P. Composition Class,P. Atmosphere Class,P. Habitable Class,P. Min Mass (EU),P. Mass (EU),P. Radius (EU),P. Density (EU),...,S. Mag from Planet,S. Size from Planet (deg),S. Hab Zone Min (AU),S. Hab Zone Max (AU),P. HZD,P. HZC,P. HZA,P. HZI,P. ESI,P. Habitable
0,1RXS 1609 b,0,0,0,0,1,1318.48628,4451.16,19.04,0.64,...,-13.2,0.0022,0.540,1.362,800.07,23.51,85.62,0.00,0.05,0
1,1SWASP J1407 b,0,0,0,0,1,6358.80000,6358.80,10.94,4.86,...,-22.5,0.1353,0.461,1.143,9.07,15.30,45.41,0.02,0.07,0
2,2M 0103-55(AB) b,0,0,0,0,1,4133.22000,4133.22,11.40,2.79,...,-13.2,0.0024,0.136,0.347,793.67,12.57,107.44,0.00,0.06,0
3,2M 0122-24 b,0,0,0,0,1,1318.48628,6358.80,11.20,4.53,...,-14.2,0.0039,0.136,0.347,490.45,15.72,119.46,0.00,0.08,0
4,2M 0219-39 b,0,0,0,0,1,1318.48628,4419.37,16.13,1.05,...,-10.1,0.0009,0.062,0.165,3028.82,19.46,133.25,0.00,0.06,0

In [72]:
df.to_csv("mixed_columns_plname.csv", index=False)